name: Generate Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Generate contribution graph
      env:
        GITHUB_USERNAME: ${{ Pulkit1822 }}
      run: |
        node index.js
        git config --global user.name "Pulkit1822"
        git config --global user.email "Pulkit1822@gmail.com"
        git add -A
        git commit -m "Updated contribution graph"
        git push
